language: node_js
node_js:
  - "8"
before_install:
  - npm install -g typescript
before_script:
  - npm run build
script:
  - npm run test
deploy:
  provider: heroku
  app: bdthomson-food-app
  skip_cleanup: true
  api_key:
    secure: r96QyTQ4cOatVuyn9IDbFvcgf+lLJLPigKRcL0TvdLbx4pGZwZ4LF/MuWez/vHmRLiHKhrkLTrxzdrZTe/5jvKTkjsKb7SlDpyCYNHzSmr7iGIvNtzsoA6C/sGcEt+5aWGGOwaDljOFiQ+yKjkL7KuDbQKx4vWKBNxAdWSS3z7w0lxSe+wuW37vSrLpbCj0HnvLwShzcfFS3FQmsYl9aEtZ93dioAKu5t/87H5/v82udRlJsnqIMjUoPJBJPeFLTrEP2Des+qI1N0azgXuNeyASfEeGw5eEnRvspE96/kKO0OLWebWD41PLUmEeD5L/chbqCgO9bdIb6kJAz/BnEELjWEfBo7xU14mgcjXgTY50uZeSnEePbCeXrLqH6JJFJfSwQzbj7Y8iEVXvYYaQjI0yGlW4tkQuKyk/CMqFVbpFRb7L5MkRM9OmSnlBmHxwbRFjwWmvN9bdasvENYNw+JVroi5jTfQmd0xlrgpVBeal74RI0fuQ0/U0i/VEEIdIhZnKBe7fsHKg8w/hw4gvsotfotZpJgTgIoasGB6Gw1cAxxmyI7z7Rz8wkQU0j/95zWTIn4ESVlSi6S/tDYZb1mWw64ml2go54VTTQ3zpKn/jW3YOcjm2SEzh0+29dTdFKt27Y9SUuU4XKg05zwdB63g4UzNBqZsyeVvIwShwYLZs=
